export { PersonSchema, personEvents, createPersonHandlers, createPersonHooks } from './domain/person'
export { createPersonService } from './application/person/personService'
export { schema } from './settings/schema'
export { createDefault as createDefaultHandlers } from './settings/handlers'
export { createDefault as createDefaultHooks } from './settings/hooks'
export { allPermissions } from './support/allPermissions'
