export const iconMap: Record<string, string> = {
  'save': 'save',
  'close': 'close',
  'x': 'close',
  'trash': 'delete',
  'trash-2': 'delete',
  'send': 'send',
  'edit': 'edit',
  'edit-2': 'edit',
  'add': 'add',
  'plus': 'add',
  'search': 'search',
  'view': 'visibility',
  'eye': 'visibility',
  'list': 'list',
  'person': 'person',
  'user': 'person',
  'map': 'place',
  'map-pin': 'place',
}
